version: '3.2'

services:
  app:
    restart: always
    # build de uma imagem local (Dockefile)
    build: .
    container_name: curso-nestjs-app
    ports:
      - "3000:3000"
    # compartilhar tudo da minha aplicação com o container
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    # acsso ao terminal do container
    tty: true
    # Espelhar a pasta do container com a pasta local
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    restart: always
    ports:
      - "15432:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres

  migration:
    build: .
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "migration:run"
      ]
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  db_data:
